module.exports = [{"id":1,"Nombre":"Goat, mountain"},
{"id":2,"Nombre":"Brocket, red"},
{"id":3,"Nombre":"Hummingbird (unidentified)"},
{"id":4,"Nombre":"Skua, long-tailed"},
{"id":5,"Nombre":"Agama lizard (unidentified)"},
{"id":6,"Nombre":"Nilgai"},
{"id":7,"Nombre":"Sambar"},
{"id":8,"Nombre":"Pale-throated three-toed sloth"},
{"id":9,"Nombre":"Barrows goldeneye"},
{"id":10,"Nombre":"Crane, sandhill"},
{"id":11,"Nombre":"Lizard, goanna"},
{"id":12,"Nombre":"Black-backed magpie"},
{"id":13,"Nombre":"Red meerkat"},
{"id":14,"Nombre":"Possum, western pygmy"},
{"id":15,"Nombre":"Small-clawed otter"},
{"id":16,"Nombre":"Bohor reedbuck"},
{"id":17,"Nombre":"Great kiskadee"},
{"id":18,"Nombre":"White-winged tern"},
{"id":19,"Nombre":"Grizzly bear"},
{"id":20,"Nombre":"Cape raven"},
{"id":21,"Nombre":"African clawless otter"},
{"id":22,"Nombre":"Feral rock pigeon"},
{"id":23,"Nombre":"Squirrel, eastern fox"},
{"id":24,"Nombre":"Kangaroo, western grey"},
{"id":25,"Nombre":"Golden brush-tailed possum"},
{"id":26,"Nombre":"Black-fronted bulbul"},
{"id":27,"Nombre":"Heron, yellow-crowned night"},
{"id":28,"Nombre":"Eagle, bald"},
{"id":29,"Nombre":"Raccoon, crab-eating"},
{"id":30,"Nombre":"Sandgrouse, yellow-throated"},
{"id":31,"Nombre":"Ox, musk"},
{"id":32,"Nombre":"Bird, magnificent frigate"},
{"id":33,"Nombre":"Cat, european wild"},
{"id":34,"Nombre":"Bohor reedbuck"},
{"id":35,"Nombre":"Leadbeateri's ground hornbill"},
{"id":36,"Nombre":"Stork, white-necked"},
{"id":37,"Nombre":"Turtle, long-necked"},
{"id":38,"Nombre":"Crab-eating fox"},
{"id":39,"Nombre":"Gnu, brindled"},
{"id":40,"Nombre":"African bush squirrel"},
{"id":41,"Nombre":"Sloth, two-toed tree"},
{"id":42,"Nombre":"Two-toed tree sloth"},
{"id":43,"Nombre":"Lemur, sportive"},
{"id":44,"Nombre":"Deer, barasingha"},
{"id":45,"Nombre":"Sea birds (unidentified)"},
{"id":46,"Nombre":"Black kite"},
{"id":47,"Nombre":"Levaillant's barbet"},
{"id":48,"Nombre":"Swan, trumpeter"},
{"id":49,"Nombre":"Booby, blue-faced"},
{"id":50,"Nombre":"Gelada baboon"},
{"id":51,"Nombre":"Iguana, common green"},
{"id":52,"Nombre":"Pied butcher bird"},
{"id":53,"Nombre":"Jackal, silver-backed"},
{"id":54,"Nombre":"Spider, wolf"},
{"id":55,"Nombre":"Booby, blue-faced"},
{"id":56,"Nombre":"Mara"},
{"id":57,"Nombre":"Baboon, savanna"},
{"id":58,"Nombre":"Grouse, greater sage"},
{"id":59,"Nombre":"Dove, ring"},
{"id":60,"Nombre":"Swamp deer"},
{"id":61,"Nombre":"Southern tamandua"},
{"id":62,"Nombre":"Red-shouldered glossy starling"},
{"id":63,"Nombre":"Trumpeter, green-winged"},
{"id":64,"Nombre":"Red-cheeked cordon bleu"},
{"id":65,"Nombre":"Thirteen-lined squirrel"},
{"id":66,"Nombre":"Common boubou shrike"},
{"id":67,"Nombre":"Colobus, white-mantled"},
{"id":68,"Nombre":"Rhea, gray"},
{"id":69,"Nombre":"European wild cat"},
{"id":70,"Nombre":"Deer, black-tailed"},
{"id":71,"Nombre":"Savanna fox"},
{"id":72,"Nombre":"Penguin, little blue"},
{"id":73,"Nombre":"Nyala"},
{"id":74,"Nombre":"Giraffe"},
{"id":75,"Nombre":"Pelican, great white"},
{"id":76,"Nombre":"Great white pelican"},
{"id":77,"Nombre":"Black-backed jackal"},
{"id":78,"Nombre":"Green heron"},
{"id":79,"Nombre":"Black-crowned night heron"},
{"id":80,"Nombre":"Whip-tailed wallaby"},
{"id":81,"Nombre":"Southern boubou"},
{"id":82,"Nombre":"Black-collared barbet"},
{"id":83,"Nombre":"Arctic tern"},
{"id":84,"Nombre":"Campo flicker"},
{"id":85,"Nombre":"Savannah deer (unidentified)"},
{"id":86,"Nombre":"Wambenger, red-tailed"},
{"id":87,"Nombre":"Dragon, frilled"},
{"id":88,"Nombre":"Gecko, barking"},
{"id":89,"Nombre":"Agile wallaby"},
{"id":90,"Nombre":"White-throated robin"},
{"id":91,"Nombre":"Wallaroo, common"},
{"id":92,"Nombre":"Bear, sloth"},
{"id":93,"Nombre":"Bleu, red-cheeked cordon"},
{"id":94,"Nombre":"Goose, canada"},
{"id":95,"Nombre":"Canada goose"},
{"id":96,"Nombre":"Silver-backed fox"},
{"id":97,"Nombre":"Barbet, crested"},
{"id":98,"Nombre":"Bustard, denham's"},
{"id":99,"Nombre":"Leopard, indian"},
{"id":100,"Nombre":"Blue waxbill"}]