module.exports = [
    {"id":1,"Nombre":"Eos","Descripcion":"Alveoloplasty"},
    {"id":2,"Nombre":"Civic","Descripcion":"Application of external fixator device, unspecified site"},
    {"id":3,"Nombre":"Talon","Descripcion":"Skeletal x-ray of wrist and hand"},
    {"id":4,"Nombre":"Navigator","Descripcion":"Small-to-small intestinal anastomosis"},
    {"id":5,"Nombre":"Vandura 1500","Descripcion":"Application of other wound dressing"},
    {"id":6,"Nombre":"Cayenne","Descripcion":"Other repair of nasal sinus"},
    {"id":7,"Nombre":"Toronado","Descripcion":"Sequestrectomy, unspecified site"},
    {"id":8,"Nombre":"Bonneville","Descripcion":"Control of hemorrhage following vascular surgery"},
    {"id":9,"Nombre":"Taurus","Descripcion":"Removal of gastrostomy tube"},
    {"id":10,"Nombre":"600","Descripcion":"Insertion of totally implantable infusion pump"},
    {"id":11,"Nombre":"Safari","Descripcion":"Continent ileostomy"},
    {"id":12,"Nombre":"Murciélago","Descripcion":"Other and open repair of indirect inguinal hernia with graft or prosthesis"},
    {"id":13,"Nombre":"Silverado 3500","Descripcion":"Open reduction of fracture with internal fixation, tarsals and metatarsals"},
    {"id":14,"Nombre":"Lumina","Descripcion":"Removal of cystostomy tube"},
    {"id":15,"Nombre":"Sigma","Descripcion":"Vesicostomy"},
    {"id":16,"Nombre":"Explorer","Descripcion":"Catheter based invasive electrophysiologic testing"},
    {"id":17,"Nombre":"Bravada","Descripcion":"Insertion of other spinal devices"},
    {"id":18,"Nombre":"RX-8","Descripcion":"Other computerized axial tomography"},
    {"id":19,"Nombre":"Seville","Descripcion":"Other incision of vulva and perineum"},
    {"id":20,"Nombre":"Town & Country","Descripcion":"Closure of salivary fistula"},
    {"id":21,"Nombre":"Grand Marquis","Descripcion":"Revision of knee replacement, patellar component"},
    {"id":22,"Nombre":"600SEL","Descripcion":"Irrigation and exploration of ventricular shunt"},
    {"id":23,"Nombre":"Camry","Descripcion":"Insertion of bone growth stimulator, tarsals and metatarsals"},
    {"id":24,"Nombre":"Taurus","Descripcion":"Suture of laceration of ureter"},
    {"id":25,"Nombre":"Aviator","Descripcion":"Skeletal series"},
    {"id":26,"Nombre":"Coupe Quattro","Descripcion":"Other scleral fistulization with iridectomy"},
    {"id":27,"Nombre":"Sonoma","Descripcion":"Closure of fistula of larynx"},
    {"id":28,"Nombre":"Grand Vitara","Descripcion":"Arteriography of placenta"},
    {"id":29,"Nombre":"300","Descripcion":"Other suture of other tendon of hand"},
    {"id":30,"Nombre":"CX","Descripcion":"Arthrotomy for removal of prosthesis without replacement, other specified sites"},
    {"id":31,"Nombre":"RSX","Descripcion":"Unspecified operation on bone injury, tibia and fibula"},
    {"id":32,"Nombre":"323","Descripcion":"Other operations on muscle, tendon, fascia, and bursa"},
    {"id":33,"Nombre":"Avalon","Descripcion":"Excision of bone for graft, patella"},
    {"id":34,"Nombre":"XG350","Descripcion":"Antesternal esophageal anastomosis with interposition of colon"},
    {"id":35,"Nombre":"Yukon XL 2500","Descripcion":"Other arthrotomy, elbow"},
    {"id":36,"Nombre":"A6","Descripcion":"Injection of other agent into spinal canal"},
    {"id":37,"Nombre":"Explorer","Descripcion":"Microscopic examination of specimen from musculoskeletal system and of joint fluid, cell block and Papanicolaou smear"},
    {"id":38,"Nombre":"Impreza","Descripcion":"Revision of knee replacement, not otherwise specified"},
    {"id":39,"Nombre":"V50","Descripcion":"Implantation or replacement of cardiac contractility modulation [CCM] rechargeable pulse generator only"},
    {"id":40,"Nombre":"LTD Crown Victoria","Descripcion":"Implantation or replacement of cochlear prosthetic device, multiple channel"},
    {"id":41,"Nombre":"Wrangler","Descripcion":"Excision or destruction of lesion of sclera"},
    {"id":42,"Nombre":"Ram 2500 Club","Descripcion":"Electroretinogram [ERG]"},
    {"id":43,"Nombre":"Caravan","Descripcion":"Biopsy of parathyroid gland"},
    {"id":44,"Nombre":"3500","Descripcion":"Closure of cholecystostomy"},
    {"id":45,"Nombre":"Yukon XL 2500","Descripcion":"Biopsy of joint structure, knee"},
    {"id":46,"Nombre":"Astro","Descripcion":"Internal fixation of bone without fracture reduction, femur"},
    {"id":47,"Nombre":"Grand Vitara","Descripcion":"Pneumoperitoneum for collapse of lung"},
    {"id":48,"Nombre":"GS","Descripcion":"Laparoscopic repair of direct inguinal hernia with graft or prosthesis"},
    {"id":49,"Nombre":"Bronco II","Descripcion":"Repair of laryngeal fracture"},
    {"id":50,"Nombre":"Tribute","Descripcion":"Digital examination of uterus"},
    {"id":51,"Nombre":"Camaro","Descripcion":"Linear repair of laceration of eyelid or eyebrow"},
    {"id":52,"Nombre":"S60","Descripcion":"Transfusion of packed cells"},
    {"id":53,"Nombre":"Sable","Descripcion":"Endoscopic retrograde pancreatography [ERP]"},
    {"id":54,"Nombre":"Vision","Descripcion":"Other diagnostic procedures on trachea"},
    {"id":55,"Nombre":"IS","Descripcion":"Vaginal construction"},
    {"id":56,"Nombre":"Prizm","Descripcion":"Closure of ureterostomy"},
    {"id":57,"Nombre":"Firefly","Descripcion":"Disarticulation of hip"},
    {"id":58,"Nombre":"SC","Descripcion":"Right heart cardiac catheterization"},
    {"id":59,"Nombre":"GS","Descripcion":"Removal of dental packing"},
    {"id":60,"Nombre":"Acclaim","Descripcion":"Other and open repair of direct inguinal hernia with graft or prosthesis"},
    {"id":61,"Nombre":"Torrent","Descripcion":"Infusion of drotrecogin alfa (activated)"},
    {"id":62,"Nombre":"Oasis","Descripcion":"Other corneal transplant"},
    {"id":63,"Nombre":"370Z","Descripcion":"Contrast vasogram"},
    {"id":64,"Nombre":"EXP","Descripcion":"Fixation of large intestine to abdominal wall"},
    {"id":65,"Nombre":"MX-5","Descripcion":"Other local excision or destruction of lesion of joint, knee"},
    {"id":66,"Nombre":"Beretta","Descripcion":"Debridement of open fracture site, phalanges of hand"},
    {"id":67,"Nombre":"F150","Descripcion":"Digital examination of enterostomy stoma"},
    {"id":68,"Nombre":"Mazda3","Descripcion":"Cardiopulmonary resuscitation, not otherwise specified"},
    {"id":69,"Nombre":"E150","Descripcion":"Apexcardiogram (with ECG lead)"},
    {"id":70,"Nombre":"Cube","Descripcion":"Pubiotomy to assist delivery"},
    {"id":71,"Nombre":"W201","Descripcion":"Intrathoracic esophagoesophagostomy"},
    {"id":72,"Nombre":"Corvette","Descripcion":"Gastric lavage"},
    {"id":73,"Nombre":"E-350 Super Duty Van","Descripcion":"Delayed opening of ileostomy"},
    {"id":74,"Nombre":"Rio","Descripcion":"Nonmechanical methods of resuscitation"},
    {"id":75,"Nombre":"Rondo","Descripcion":"Fasciotomy of hand"},
    {"id":76,"Nombre":"9-3","Descripcion":"Other computerized axial tomography"},
    {"id":77,"Nombre":"Grand Prix","Descripcion":"Other auditory and vestibular function tests"},
    {"id":78,"Nombre":"626","Descripcion":"Removal of intraluminal foreign body from vagina without incision"},
    {"id":79,"Nombre":"C70","Descripcion":"Removal of residual root"},
    {"id":80,"Nombre":"Yaris","Descripcion":"Local perfusion of large intestine"},
    {"id":81,"Nombre":"911","Descripcion":"Other antesternal esophageal anastomosis with interposition"},
    {"id":82,"Nombre":"A5","Descripcion":"Fracture of the turbinates"},
    {"id":83,"Nombre":"TL","Descripcion":"Psychiatric commitment evaluation"},
    {"id":84,"Nombre":"IPL G","Descripcion":"Other endovascular procedures on other vessels"},
    {"id":85,"Nombre":"Eos","Descripcion":"Microscopic examination of specimen from trachea, bronchus, pleura, lung, and other thoracic specimen, and of sputum, culture and sensitivity"},
    {"id":86,"Nombre":"Ascender","Descripcion":"Suture of laceration of palate"},
    {"id":87,"Nombre":"X5","Descripcion":"Bursectomy"},
    {"id":88,"Nombre":"ES","Descripcion":"Contrast radiogram of mammary ducts"},
    {"id":89,"Nombre":"MDX","Descripcion":"Injection or infusion of glucarpidase"},
    {"id":90,"Nombre":"Voyager","Descripcion":"Injection of other anti-infective"},
    {"id":91,"Nombre":"S-Series","Descripcion":"Other partial thyroidectomy"},
    {"id":92,"Nombre":"Silhouette","Descripcion":"Localized perfusion of liver"},
    {"id":93,"Nombre":"F150","Descripcion":"Other transmyocardial revascularization"},
    {"id":94,"Nombre":"A8","Descripcion":"Synovectomy, wrist"},
    {"id":95,"Nombre":"Eldorado","Descripcion":"Complete laryngectomy"},
    {"id":96,"Nombre":"GX","Descripcion":"Replacement or repair of thoracic unit of (total) replacement heart system"},
    {"id":97,"Nombre":"2500","Descripcion":"Microscopic examination of specimen from other site, culture"},
    {"id":98,"Nombre":"Bravada","Descripcion":"Other diagnostic procedures on cornea"},
    {"id":99,"Nombre":"Bravada","Descripcion":"Other procedures for creation of esophagogastric sphincteric competence"},
    {"id":100,"Nombre":"Fleetwood","Descripcion":"Open reduction of maxillary fracture"}] 